version: build '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
configuration: Release
platform: Any CPU
shallow_clone: true
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore src\ExtensionTool\ExtensionTool.sln
build:
  project: src/AwesomeProxy.sln
  publish_azure_webjob: true
  verbosity: minimal
deploy:
- provider: NuGet
  server: https://api.nuget.org/v3/index.json
  api_key:
    secure: oZ0W/lO60ivXmzYEYAw0CEd8225s5BVgkTwsubzPKesVTBqsNbC4LwJIeci9QC3r
  skip_symbols: false
  on:
    branch: master